-- 1) Supabase SQL Editor에서 이 파일 전체를 실행하세요.
-- 친구 둘이 사용하는 작은 1:1 버블형 앱용 스키마입니다.
-- 기본 가입은 fan이며, 친구의 계정을 만든 뒤 아래의 UPDATE로 artist로 바꿀 수 있습니다.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'fan' check (role in ('fan','artist')),
  display_name text not null default '',
  nickname text not null default '',
  avatar_url text,
  subscription_started_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  fan_id uuid not null references public.profiles(id) on delete cascade,
  artist_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(fan_id, artist_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  reply_to_id bigint references public.messages(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- profiles: 로그인한 사용자는 프로필을 읽을 수 있음.
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

-- 본인 프로필만 생성/수정 가능. 가입 시 role은 fan으로만 만들 수 있게 함.
create policy "profiles_insert_self_as_fan"
on public.profiles for insert
to authenticated
with check (id = auth.uid() and role = 'fan');

create policy "profiles_update_self"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- conversation은 당사자만 읽을 수 있음.
create policy "conversation_select_participant"
on public.conversations for select
to authenticated
using (fan_id = auth.uid() or artist_id = auth.uid());

create policy "conversation_insert_participant"
on public.conversations for insert
to authenticated
with check (fan_id = auth.uid() or artist_id = auth.uid());

-- messages는 해당 대화의 fan/artist만 읽고 보낼 수 있음.
create policy "messages_select_participant"
on public.messages for select
to authenticated
using (
  exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.fan_id = auth.uid() or c.artist_id = auth.uid())
  )
);

create policy "messages_insert_participant"
on public.messages for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.fan_id = auth.uid() or c.artist_id = auth.uid())
  )
);

-- Realtime에서 messages 변경을 받을 수 있게 publication에 추가.
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then
  null;
end $$;

-- ============================================
-- 친구 계정을 artist로 바꾸는 방법
-- ============================================
-- 친구가 회원가입한 뒤 profiles의 id를 확인하고 아래처럼 실행하세요.
-- UPDATE public.profiles
-- SET role = 'artist'
-- WHERE id = '친구의-UUID';

-- 구독 시작일을 원하는 날짜로 맞추고 싶다면:
-- UPDATE public.profiles
-- SET subscription_started_at = '2026-10-02T00:00:00+09:00'
-- WHERE id = '팬의-UUID';
